### PR TITLE
Create repositories-relationship.md

### PR DESCRIPTION
**Pull request by yusukefs**
ドキュメント用にリポジトリ間の関係性の図を追加

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/docs/pull/3#" title="Author self-approved">yusukefs</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fdocs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/dataware-tools/docs/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by yusukefs** [comment]
GitBook用のMermaidプラグインが軒並みメンテされていなかったため、理想的ではないのですがGitBookからこちらのマークダウンへのリンクを貼ろうと思っていますがいかがでしょう？

**Comment by d-hayashi** [comment]
LGTM!

> GitBookからこちらのマークダウンへのリンクを貼ろうと思っていますがいかがでしょう？

問題ないかと思います！   
~~もしGitBook上に表示したい場合は Gist にして Mermaid公式の Live Editor にレンダリングしてもらうのもありかも？  
https://mermaid-js.github.io/mermaid/#/n00b-gettingStarted?id=loading-from-gists~~

↑よく考えたらGitBookにHTMLの埋め込みできないから Mermaid の Live Editor 使っても意味ないですね。。

**Review by d-hayashi — APPROVED** [review]

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/docs/pull/3#pullrequestreview-965557092" title="Approved">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/docs/pull/3#" title="Author self-approved">yusukefs</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fdocs).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/dataware-tools/docs/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
